### ISSUE TITLE
[BUG] Problem when i draw room into room

### ISSUE THREAD

**Issue by AnthonyBASTIDE** [cvdlab/react-planner#104] opened 2018-03-16 10:31 UTC
Hello everyone,

I have problem when i try to make a room into an another room, i recorded the scene : https://webmshare.com/dvAYY

(sorry for my english, i'm french).

Have a nice day.
Regards, Anthony.

**Comment by danilosalvati** [comment] 2018-03-16 10:59
Hi @AnthonyBASTIDE,
this is caused by a bug we had already solved in past versions of the software, probably one of our last commits caused the regression. I will take a look soon...

**Comment by alessiocarrafa** [comment] 2018-03-16 15:00
Should be fixed with 1.7.2 version

**Closed by alessiocarrafa** 2018-03-16 15:00 UTC

**Comment by AnthonyBASTIDE** [comment] 2018-03-16 15:42
Thanks guys, now it's ok. 

Have a nice day.
Regards, Anthony.
